name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    types: [ checks_requested ]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        java:
          # Keep this list as: all supported LTS JDKs, the latest GA JDK, and the latest EA JDK (optional).
          - 11
          - 17
          - 21
          - 23
        container:
          - wildfly-managed
          - tomee-managed
        browser:
          - htmlUnit
          - chrome
          - firefox
    steps:
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-firefox@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress --activate-profiles ${{ matrix.container }} --define arquillian.drone.browser=${{ matrix.browser }} verify
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.container }}-${{ matrix.browser }}
          path: '**/surefire-reports/*.txt'
